services:
  api-service:
    build:
      context: .
    container_name: x-service
    ports:
      - "3000:3000"
    env_file: .env.x.local
    volumes:
      - ../../../tmp/shared:/app/content
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health/"]
      interval: 5s
      timeout: 5s
      retries: 5